### ISSUE TITLE
Text should be aligned to the left and not "justified"

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/cim_github_pages#13]
![image](https://user-images.githubusercontent.com/3258579/118880766-179ac400-b8a7-11eb-88a0-c9b1f04511ea.png)

**Comment by jpradocueva** [comment]
As before, please indicate which change you have done.

The easy way to do it now that the commit is done directly is by indicating a link from the "history" that contains the changes.
https://github.com/standards-hub/cim_github_pages/commit/d3044a7181d68b1cfce0781134bf0be187405bb1#diff-e73b35364c60ba845bb11a95b54e7b8e0439b5aafc61723021cd0ea7b56a709c

Also, please use brief commits descriptions that it is relevant to the changes. These are good developer's practice. :)

**Comment by ladyvargas** [comment]
https://github.com/standards-hub/cim_github_pages/commit/18d2c60284460d3ab2f205f8827ff97556d7f159?branch=18d2c60284460d3ab2f205f8827ff97556d7f159&diff=split

**Comment by jpradocueva** [comment]
done
