### ISSUE TITLE
Add favicon for CIM

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/cim_github_pages#15]

**Comment by jpradocueva** [comment]
@ladyvargas please indicate here the PR that contains the solution to the problem. In this way, I can see what files and code have been added or modified.

**Comment by jpradocueva** [comment]
the easy way to create a PR is.
Pull the latest changes from the repo, then create a new local branch.
Add the changes to your new local branch
Then, push the new local branch to the repo,
Then, create a PR from the local branch to the "gh-pages" branch or whatever is the branch that receives the changes. 

In this way, I am able to see what are the changes that you are proposing, which files are modified.

**Comment by ladyvargas** [comment]
https://github.com/standards-hub/cim_github_pages/commit/d3044a7181d68b1cfce0781134bf0be187405bb1#diff-e73b35364c60ba845bb11a95b54e7b8e0439b5aafc61723021cd0ea7b56a709c

**Comment by jpradocueva** [comment]
Update to layouts/home.html, line 10, <link rel="shortcut icon" type="image/png" href="./img/cim-color.png">
