### ISSUE TITLE
Add Category

### ISSUE THREAD

**Issue by ladyvargas** [standards-hub/cim_github_pages#16]
[https://cloudinformationmodel.github.io/documentation/](url)

**Comment by jpradocueva** [comment]
Add commit or PR.

**Comment by ladyvargas** [comment]
[https://github.com/cloudinformationmodel/documentation/commit/d44110a26754ef63fb46d6b3a8e640bd17baa3d2](url)
[https://github.com/cloudinformationmodel/documentation/commit/5d666c1191875b7af0f228512d91029291a907fb](url)
[https://github.com/cloudinformationmodel/documentation/commit/403697f71f9c291faf75c551457334b5bb8e19b8](url)
[https://github.com/cloudinformationmodel/documentation/commit/b503dde09aceed70ee17f8c0a1d3fbff6e5e5818](url)
[](url)

**Comment by jpradocueva** [comment]
@ladyvargas I don't see the content of the changes by clicking the above links. None of them show any content. Where these links should be pointing to?

**Comment by ladyvargas** [comment]
[d44110a26754ef63fb46d6b3a8e640bd17baa3d2](url)

**Comment by ladyvargas** [comment]
Al parecer hubo un error en los links
[https://github.com/cloudinformationmodel/documentation/commit/d44110a26754ef63fb46d6b3a8e640bd17baa3d2](url)

**Comment by ladyvargas** [comment]
No se porque no sale el link, ya que está correcto
