### ISSUE TITLE
layouts/home.html needs to be update with simplified code

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/cim_github_pages#17]
It seems that this file layouts/home.html has not been updated with the changes suggested by Dejan in PR https://github.com/standards-hub/cim_github_pages/pull/2.

**Comment by jpradocueva** [comment]
Add a link to PR or commit

**Comment by ladyvargas** [comment]
#21

**Comment by jpradocueva** [comment]
Changes were already applied directly to files in 'gh-pages' #21 is a demo PR.
