### ISSUE TITLE
ALERT: We found potential security vulnerabilities in your dependencies.

### ISSUE THREAD

**Issue by ladyvargas** [standards-hub/cim_github_pages#31]

**Comment by jpradocueva** [comment]
https://github.com/standards-hub/cim_github_pages/security/dependabot
- [x] https://github.com/standards-hub/cim_github_pages/security/dependabot/Gemfile.lock/rexml/open
- [x] https://github.com/standards-hub/cim_github_pages/security/dependabot/Gemfile.lock/kramdown/open

**Comment by jpradocueva** [comment]
@ladyvargas que tengo que hacer?

**Comment by ladyvargas** [comment]
@jpradocueva  Ya están resueltos
